=== uarg-unpa/LABOO/tp2/punto3/serie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoCodigo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoGeneroSerie">
        <xs:restriction base="xs:string">
            <xs:enumeration value="acción"/>
            <xs:enumeration value="drama"/>
            <xs:enumeration value="ciencia ficción"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoGeneroPersonaje">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="O"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoRolPersonaje">
        <xs:restriction base="xs:string">
            <xs:enumeration value="principal"/>
            <xs:enumeration value="secundario"/>
            <xs:enumeration value="reparto"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="serie">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="personajes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="personaje" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="género" type="tipoGeneroPersonaje"/>
                                        <xs:element name="descripción" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="tipo" type="tipoRolPersonaje" default="principal"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="trama" type="xs:string"/>

                <xs:element name="hashtag" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="cod" type="tipoCodigo" use="required"/> <xs:attribute name="título" type="xs:string" use="required"/> <xs:attribute name="género" type="tipoGeneroSerie" use="optional"/> </xs:complexType>
    </xs:element>

</xs:schema>

=== uarg-unpa/LABOO/tp2/punto3/peaky_blinders.xml
<?xml version="1.0" encoding="UTF-8"?>
<serie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="serie.xsd" 
       cod="P88" título="Peaky Blinders" género="drama">
    
    <personajes>
        <personaje id="p3" tipo="principal">
            <nombre>Thomas Shelby</nombre>
            <género>M</género>
            <descripción>Líder de la banda criminal Peaky Blinders.</descripción>
        </personaje>
        <personaje id="p4" tipo="secundario">
            <nombre>Ada Thorne</nombre>
            <género>F</género>
        </personaje>
    </personajes>
    
    <trama>Una familia de gánsteres asienta su dominio en Birmingham justo después de la Primera Guerra Mundial.</trama>
    
</serie>

=== uarg-unpa/LABOO/tp2/punto3/the_last_of_us.xml
<?xml version="1.0" encoding="UTF-8"?>
<serie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="serie.xsd" 
       cod="T01" título="The Last of Us" género="ciencia ficción">
    
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Joel Miller</nombre>
            <género>M</género>
            <descripción>Contrabandista encargado de escoltar a Ellie.</descripción>
        </personaje>
        <personaje id="p2" tipo="principal">
            <nombre>Ellie Williams</nombre>
            <género>F</género>
        </personaje>
    </personajes>
    
    <trama>Veinte años después de que una pandemia fúngica destruyera la civilización moderna, un superviviente es contratado para sacar de contrabando a una niña.</trama>
    
    <hashtag nombre="Supervivencia"/>
    <hashtag nombre="Infectados"/>
</serie>
