=== uarg-unpa/LABOO/tp2/punto1/seleccion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoID">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoEdad">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTexto20">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTexto30">
        <xs:restriction base="xs:string">
            <xs:maxLength value="30"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="seleccion">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="equipos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="tipoID"/>
                                        <xs:element name="nombre" type="tipoTexto30"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="jugadores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jugador" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="tipoID"/>
                                        <xs:element name="apellido" type="tipoTexto20"/>
                                        <xs:element name="nombre" type="tipoTexto30"/>
                                        <xs:element name="posicion" type="tipoTexto20"/>
                                        <xs:element name="edad" type="tipoEdad"/>
                                        <xs:element name="equipo_id" type="tipoID"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== uarg-unpa/LABOO/tp2/punto1/seleccion.xml
<?xml version="1.0" encoding="UTF-8"?>
<seleccion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="seleccion.xsd">
    
    <equipos>
        <equipo>
            <id>1</id>
            <nombre>Inter Miami CF</nombre>
        </equipo>
        <equipo>
            <id>2</id>
            <nombre>Aston Villa</nombre>
        </equipo>
    </equipos>

    <jugadores>
        <jugador>
            <id>10</id>
            <apellido>Messi</apellido>
            <nombre>Lionel</nombre>
            <posicion>Delantero</posicion>
            <edad>36</edad>
            <equipo_id>1</equipo_id>
        </jugador>
        <jugador>
            <id>23</id>
            <apellido>Martinez</apellido>
            <nombre>Emiliano</nombre>
            <posicion>Arquero</posicion>
            <edad>31</edad>
            <equipo_id>2</equipo_id>
        </jugador>
    </jugadores>
    
</seleccion>
